name: "Action PR Conventional"
description: "Opinionated PR title validation with semantic format, configurable lowercase subject, imperative verb, and optional issue suffix."

inputs:
  issue-prefix:
    description: "Optional issue prefix for a suffix at the end of the subject (for example, PROJ- to allow '... PROJ-123')."
    required: false
    default: ""
  issue-mode:
    description: "Issue suffix policy: 'optional' or 'required'."
    required: false
    default: "optional"
  issue-unknown:
    description: "Whether unknown issue-like suffixes are allowed (`true` or `false`)."
    required: false
    default: "false"
  enforce-lowercase:
    description: "Whether the PR subject must be lowercase (`true` or `false`)."
    required: false
    default: "true"
  verbs:
    description: "Optional comma-separated list of allowed imperative verbs. Overrides the default list."
    required: false
    default: ""
  add-verbs:
    description: "Optional comma-separated list of imperative verbs to add to the default list."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate semantic PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Validate imperative subject
      shell: bash
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
        ISSUE_PREFIX: ${{ inputs.issue-prefix }}
        ISSUE_MODE: ${{ inputs.issue-mode }}
        ISSUE_UNKNOWN: ${{ inputs.issue-unknown }}
        ENFORCE_LOWERCASE: ${{ inputs.enforce-lowercase }}
        VERBS: ${{ inputs.verbs }}
        ADD_VERBS: ${{ inputs.add-verbs }}
      run: node "${{ github.action_path }}/dist/index.cjs"
